# RemoveCollisionObject.srv

# Request
string id                      # Unique identifier of the object to remove

---
# Response
bool success                   # Indicate if the object was removed successfully
string message                 # Additional information or error messages
