# AddCollisionObject.srv

# Request
string id                      # Unique identifier for the object
string shape                   # Shape type: box, cylinder, sphere
float64[] dimensions           # Dimensions corresponding to the shape
geometry_msgs/Pose pose        # Pose of the object

---
# Response
bool success                   # Indicate if the object was added successfully
string message                 # Additional information or error messages
