objects:
  - name: "obstacle_ground"
    type: "box"
    dimensions: [0.8, 0.8, 0.1]
    pose:
      position: {x: 0.0, y: 0.0, z: -0.05}
      orientation: {roll: 0.0, pitch: 0.0, yaw: 0.0}

  - name: "obstacle_wall"
    type: "box"
    dimensions: [0.8, 0.02, 0.8]
    pose:
      position: {x: 0.0, y: 0.4, z: 0.3}
      orientation: {roll: 0.0, pitch: 0.0, yaw: 0.0}

  - name: "graspable_cylinder"
    type: "cylinder"
    dimensions: [0.1, 0.005]
    pose:
      position: {x: 0.0, y: 0.2, z: 0.005}
      orientation: {roll: 0.0, pitch: 1.57, yaw: 0.0}

# example for random object  
  # - name: "graspable_random_cylinder"
  #   type: "cylinder"
  #   dimensions: [0.1, 0.005]
  #   # No pose provided; will be placed randomly

# example for sphere object:  
  # - name: "custom_sphere"
  #   type: "sphere"
  #   dimensions: [0.05]
  #   pose:
  #     position: {x: 0.2, y: 0.2, z: 0.05}
  #     orientation: {roll: 0.0, pitch: 0.0, yaw: 1.57}
